<a href="https://colab.research.google.com/github/Alepescinaa/ScientificTools/blob/main/Project1/Cp2/PINN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises: physics-informed neural network

Exercise on the implementation of physics-informed neural network.

Date: 2024

Course: 056936 - SCIENTIFIC COMPUTING TOOLS FOR ADVANCED MATHEMATICAL MODELLING (PAGANI STEFANO) [2023-24].

Example adapted from this [notebook](https://colab.research.google.com/drive/1qBrbgevkSBqqYc8bOPiaoJG1MBrBrluN?usp=share_link).


Let us consider the problem

\begin{aligned}
  & v_f *\sqrt(\nabla u\cdot D\nabla u) =1  \,, \quad (x,y) \in [-1.5,1.5] \times [-1.5,1.5]\,\\
\end{aligned}

where $\nu$ is unknown. We consider the PINN framework for solving the state/parameter estimation.

In [3]:
# import required libraries

import tensorflow as tf
import numpy as np
import scipy.io
from tensorflow import keras
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
!pip -q install pyDOE
from pyDOE import lhs  # for latin hypercube sampling


In [4]:
# set seed for reproducibility
tf.random.set_seed(42)
np.random.seed(42)

In [6]:
!git clone https://github.com/Alepescinaa/ScientificTools
%cd ScientificTools/Project1/Cp2

fatal: destination path 'ScientificTools' already exists and is not an empty directory.
/content/ScientificTools/Project1/Cp2


In [7]:
# loading of the dataset

CP2data = np.load("CP2data.npz")
CP2data = CP2data['arr_0']

In [8]:
# loading of the estimate

CP2estimate = np.load("CP2estimate.npz")
CP2estimate = CP2estimate['arr_0']

In [9]:
CP2estimate[4]

array([0.1226488 , 3.6316356 , 0.84714825])

# Solution

In [21]:
X, Y = np.meshgrid(np.linspace(-1.5,1.5,1501), np.linspace(-1.5,1.5,1501))
X_flat = tf.convert_to_tensor(np.hstack((X.flatten()[:,None],Y.flatten()[:,None])),dtype=tf.float64)
x0 = 1.5
#activation_time = anysotropic_FMM( x0 , y0 , X, Y, sigma_11,sigma_12, sigma_21, sigma_22 )

In [22]:
# PINN loss function
def loss(xcl,ycl,xmeas,ymeas,umeas,param):
    umeas_pred = PINN(tf.concat([xmeas,ymeas],1))
    r_pred   = r_PINN(xcl,ycl,param)

    # loss components
    mse_meas  = tf.reduce_mean(tf.pow(umeas-umeas_pred,2))
    mse_r  = tf.reduce_mean(tf.pow(r_pred,2))

    # bc

    mse_bc= tf.pow( PINN( tf.transpose( tf.stack( [tf.constant([1.5],dtype=tf.float64), param[2] ] ) ) ) ,2)


    return mse_r + mse_meas + mse_bc # mse_0+mse_r+mse_lb+mse_ub

# neural network weight gradients
@tf.function
def grad(model,xcl,ycl,xmeas,ymeas,umeas,param):
    with tf.GradientTape(persistent=True) as tape:
        loss_value = loss(xcl,ycl,xmeas,ymeas,umeas,param)
        grads = tape.gradient(loss_value,model.trainable_variables)
        grad_param = tape.gradient(loss_value,param)
    return loss_value, grads, grad_param

In [23]:
# collocation points
Ncl = 5000
Xcl = lhs(2,Ncl)
xcl = tf.expand_dims(tf.cast(-1.5+(3.0)*Xcl[:,0],dtype=tf.float64),axis=-1)
ycl = tf.expand_dims(tf.cast(-1.5+(3.0)*Xcl[:,1],dtype=tf.float64),axis=-1)
X_coll = tf.concat([xcl,ycl],1)

# measurement points
ind_disp=4
xmeas = CP2data[ind_disp][0]
ymeas = CP2data[ind_disp][1]
tmeas = CP2data[ind_disp][2]
xmeas = tf.constant(xmeas.reshape(20, 1), dtype=tf.float64)
ymeas = tf.constant(ymeas.reshape(20, 1), dtype=tf.float64)
tmeas = tf.constant(tmeas.reshape(20, 1), dtype=tf.float64)

In [24]:
# training loop

from tensorflow.keras import regularizers

regularization_strength = 0.01

PINN = tf.keras.Sequential([
    tf.keras.layers.Dense(8, activation='tanh', input_shape=(2,),
                          kernel_initializer="glorot_normal",
                          kernel_regularizer=regularizers.l2(regularization_strength),
                          dtype=tf.float64),
    tf.keras.layers.Dense(32, activation='tanh',
                          kernel_initializer="glorot_normal",
                          kernel_regularizer=regularizers.l2(regularization_strength),
                          dtype=tf.float64),
    tf.keras.layers.Dense(1, activation=None,
                          kernel_initializer="glorot_normal",
                          kernel_regularizer=regularizers.l2(regularization_strength),
                          dtype=tf.float64)])

In [25]:
# residual computation based on AD
@tf.function
def r_PINN(x,y,param):
    u = PINN(tf.concat([x,y], 1))
    u_x = tf.gradients(u,x)[0]
    u_y = tf.gradients(u,y)[0]
    u_grad = tf.transpose(tf.concat([u_x, u_y], axis=1))

    theta0 = pi/2 - param[0]
    a = tf.stack([tf.cos(theta0), tf.sin(theta0)])
    b = tf.stack([tf.cos(theta0-pi/2), tf.sin(theta0-pi/2)])

    D = ((1/param[1])* tf.linalg.matmul(a,tf.transpose(a)) + tf.linalg.matmul(b,tf.transpose(b)))

    return  tf.linalg.matmul(tf.transpose(u_grad), tf.linalg.matmul(D,u_grad)) - 1/100**2 #check gradient shape

# Adam optimizer
tf_optimizer = tf.keras.optimizers.Adam(learning_rate=0.003,beta_1=0.99)

# parameter variable try ( 1.45816415][ 3.84494007][-0.95064015]])
#param 0 -> fiber anlge (-pi/10,pi/10)
#param 1-> aniso (0,1)
#param 2-> source y0 (-1.5,1,5)
pi = tf.constant(np.pi,dtype=tf.float64)
param = tf.Variable([[1.458], [3.84], [-0.95]], trainable=True,dtype=tf.float64)

for iter in range(5000):

  # compute gradients using AD
  loss_value,grads,grad_param = grad(PINN,xcl,ycl,xmeas,ymeas,tmeas,param)

  # update neural network weights
  tf_optimizer.apply_gradients(zip(grads+[grad_param],PINN.trainable_variables+[param]))



  # display intermediate results
  if ((iter+1) % 20 == 0):
    print('iter =  '+str(iter+1))
    #loss_value_np=loss_value.numpy()
    #print('loss = {:.4f}'.format(loss_value_np ))
    tf.print('loss=' ,loss_value)

    print(param.numpy())
    PINN_flat = PINN(X_flat)

    mse = 0.0
    time_pred = tf.reshape(PINN_flat, (1501, 1501))
    xmeas=xmeas.numpy().squeeze()
    ymeas=ymeas.numpy().squeeze()
    tmeas=tmeas.numpy().squeeze()
    time_pred=time_pred.numpy()
    for k in range(20):
            i, j = np.where((X == xmeas[k]) & (Y == ymeas[k]))
            mse+= (time_pred[i, j] - tmeas[k]) ** 2
    print('mse error: %.4e' % (np.sqrt(mse/20)))
    xmeas = tf.constant(xmeas.reshape(20, 1), dtype=tf.float64)
    ymeas = tf.constant(ymeas.reshape(20, 1), dtype=tf.float64)
    tmeas = tf.constant(tmeas.reshape(20, 1), dtype=tf.float64)


iter =  20
loss= [[0.46525961827804885]]
[[ 1.50011919]
 [ 3.88129271]
 [-0.90189427]]


<ipython-input-25-e881f4a20fac>:56: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print('mse error: %.4e' % (np.sqrt(mse/20)))


mse error: 3.6638e-01
iter =  40
loss= [[0.15603537978115342]]
[[ 1.52221948]
 [ 3.90304147]
 [-0.86656795]]
mse error: 1.9336e-01
iter =  60
loss= [[0.16890992514317649]]
[[ 1.53793072]
 [ 3.91866642]
 [-0.83275482]]
mse error: 2.5469e-01
iter =  80
loss= [[0.17556501796024909]]
[[ 1.54959567]
 [ 3.9309421 ]
 [-0.81644661]]
mse error: 2.1677e-01
iter =  100
loss= [[0.011418040913006106]]
[[ 1.55874347]
 [ 3.94080432]
 [-0.80955034]]
mse error: 1.0184e-01
iter =  120
loss= [[0.0732597515755971]]
[[ 1.56614631]
 [ 3.9488114 ]
 [-0.80473192]]
mse error: 1.5676e-01
iter =  140
loss= [[0.081941867276256769]]
[[ 1.57222703]
 [ 3.95555051]
 [-0.80310417]]
mse error: 1.6324e-01
iter =  160
loss= [[0.017882907831091661]]
[[ 1.57723755]
 [ 3.9613028 ]
 [-0.80540012]]
mse error: 1.0280e-01
iter =  180
loss= [[0.010363458067766264]]
[[ 1.58138432]
 [ 3.96614   ]
 [-0.80865453]]
mse error: 5.5194e-02
iter =  200
loss= [[0.032829177708831779]]
[[ 1.58484504]
 [ 3.97018568]
 [-0.81002   ]]
mse error

In [ ]:
#Display results

N_h = 150
X_plot, Y_plot = np.meshgrid(np.linspace(-1.5,1.5,1501), np.linspace(-1.5,1.5,1501))

fig = plt.figure(figsize=(16,9),dpi=150)
#fig = plt.figure()
#fig.subplots_adjust(wspace=0.3)
plt.style.use('default')
ax = fig.add_subplot(1,3,1)
ax.set_aspect(1)
im = plt.pcolor(X_plot, Y_plot, u_true)
plt.scatter(xmeas,ymeas,marker='x',s=3)
divider = make_axes_locatable(ax)
cax = divider.append_axes("right", size="5%", pad=0.05)
fig.colorbar(im,cax=cax)
#ax.set_yticklabels(['-1.0','-0.6','-0.2','0.2','0.6','1.0'])
ax.set_title('Exact Solution',fontsize=16)

ax = fig.add_subplot(1,3,2)
ax.set_aspect(1)
im = plt.pcolor(X_plot, Y_plot, np.reshape(PINN_flat,(N_h,N_h)))
plt.scatter(xmeas,ymeas,marker='x',s=3)
divider = make_axes_locatable(ax)
cax = divider.append_axes("right", size="5%", pad=0.05)
fig.colorbar(im,cax=cax)
ax.set_title('PINN Prediction'.format(err),fontsize=16)

ax = fig.add_subplot(1,3,3)
ax.set_aspect(1)
im = plt.pcolor(X_plot, Y_plot, np.abs( np.reshape(PINN_flat,(N_h,N_h)) -u_true ) )
divider = make_axes_locatable(ax)
cax = divider.append_axes("right", size="5%", pad=0.05)
fig.colorbar(im,cax=cax)
ax.set_title('L2 error = {:.4f}'.format(err),fontsize=16)

scale parametri
inizializzazione parametri incogniti ma nontrainable
